#!/usr/bin/env bash

echo "======================================================="
echo "Test 1"
echo 
java -jar Test1.jar | python Test1.py
echo "======================================================="