#!/usr/bin/env bash

java -jar Test1.jar > output1.txt

echo "======================================================="
echo "Test 1"
echo 
python Test2.py < output1.txt
echo "======================================================="

echo "======================================================="
echo "Test 1"
echo 
python Test2.py < output1.txt
echo "======================================================="